protected/controllers/ExercisesController.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: dimon
 * Date: 08.09.13
 * Time: 0:14
 * To change this template use File | Settings | File Templates.
 */

class ExercisesController extends CController {

    function actionIndex(){

        $criteria = new CDbCriteria;
        $criteria->select = 'id, title';

        $muscles = Muscle::model()->findAll($criteria);

        $this->render('index', array('muscles' => $muscles));
    }

    function actionMuscle($muscle_id){

        $exercises = Exercise::model()->findAllByAttributes(array('muscle_id' => $muscle_id));

        $this->render('exercises_list', array('exercises' => $exercises));
    }
}

protected/views/exercises/exercises_list.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: dimon
 * Date: 08.09.13
 * Time: 16:37
 * To change this template use File | Settings | File Templates.
 */
?>
<div class="row short-exercise">
<?php foreach($exercises as $exercise): ?>

    <article class="col-md-5">
        <h5><?php echo $exercise->title; ?></h5>

        <div class="row">
            <div class="col-md-6"><img src="http://placekitten.com/250/250" /></div>
            <div class="col-md-6">
                <p>Тип: базовое</p>
                <p>Оборудование: скамья, штанга</p>
            </div>
        </div>
        <div class="row">
            Some text
        </div>

        <div class="rating"></div>
    </article>

<?php endforeach; ?>
</div>

protected/views/exercises/index.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: dimon
 * Date: 08.09.13
 * Time: 14:37
 * To change this template use File | Settings | File Templates.
 */
?>

<h1>exercise list</h1>

<?php foreach($muscles as $muscle): ?>

    <p><?php echo B3Html::link($muscle->title, $this->createUrl('exercises/muscle',array('id'=> $muscle->id))); ?></p>

<?php endforeach; ?>